name: "GitHub Shared Repo Upload Action"
description: "Helps with Maven uploading to organiation-wide GitHub Packages repos."
author: "geiremb@gmail.com"
inputs:
  repo_name:
    description: "Local path of the shared repo to use (organization / repo)."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
